// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkqdrhygprvbdgzwuzfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcWRyaHlncHJ2YmRnend1emZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDY2MjcsImV4cCI6MjA2OTg4MjYyN30.0bOsnJcCKZ7Y0ni7k3gbfpVjjpbZ4tb9tURxTUU6UeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});